# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Capri Customizer"
handle = "capri-customizer"
client_id = "b60827152e7e4cb3b31ed8f2fa409874"
application_url = "https://holidays-activity-plus-bacon.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_draft_orders,write_orders"

[auth]
redirect_urls = [
  "https://holidays-activity-plus-bacon.trycloudflare.com/auth/callback",
  "https://holidays-activity-plus-bacon.trycloudflare.com/auth/shopify/callback",
  "https://holidays-activity-plus-bacon.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
