runtime: nodejs20

instance_class: F2

env_variables:
  NODE_ENV: "production"
  GCS_BUCKET_NAME: "capri-customizer-images"
  GCS_PROJECT_ID: "capri-customizer"
  USE_MOCK_STORAGE: "true"
  PORT: "8080"

handlers:
  - url: /build/.*
    static_dir: build
    secure: always

  - url: /public/.*
    static_dir: public
    secure: always

  - url: /.*
    script: auto
    secure: always 